### ISSUE TITLE
Blockbuster position issues with Mr. Crayfish's Furniture Mod

### ISSUE THREAD

**Issue by jeffstienstra** [mchorse/mchorse.github.io#1]
Hi McHorse!  
2 quick things: I noticed some character position issues while sitting when using Mr. Crayfish's furniture mod v4.1.1 with MC 1.10.2.

1. Actors are able to place the items from the mod and use chairs appropriately (sit) while recording, however the playback of that recording shows the actor standing on the chair and does not initiate the "sitting" position.

2.  Actors can use existing minecarts or boats (though the boat's oars don't move) but they cannot place a new one as part of their recording.  They will still follow the path their cart/boat took during recording but they will be walking the path...without a cart or boat visible.

Any way to resolve these issues?  This would allow numerous background actors in scenes like restaurants, cafes, offices, theaters etc.  I know your time is limited and fixing bugs for every possible scenario may be impossible, but I think actors sitting properly is pretty critical.  Thanks for all your hard work!

Sir_KnightyNight

**Comment by mchorse** [comment]
@Sir-KnightyNight

1. Actors are actually able to view the riding pose, AFAIK (😆), but there might be a different way that MrCrafish's mod implements player's sitting. I'll check it out after I'll finish with current update (it's almost ready, but I stumbled upon some complications).
2. Actors can't spawn the boat, because I haven't implemented item use action, yet. For placing boats, I think you'll have to find a workaround. I'll implement a command action for the next update, so people will be able to make some workarounds for their machinimas, but I know it's kind of hack-ish, but currently I can't do that much. I already delayed current update for so long.

I really appreciate your appreciation of my time, understanding and thanks for clearly phrasing the issue 👍

**Comment by jeffstienstra** [comment]
No problem.  I know how "fun" it can be to decipher a 7-paragraph sob story that never gets to the point...![image](https://cloud.githubusercontent.com/assets/25387237/22378345/56ea5c1c-e483-11e6-9f0e-1c4d1ca5b09b.png)

Looking forward to the update!

**Comment by mchorse** [comment]
@Sir-KnightyNight oh, Jeff.Beats.Minecraft, is that you? 😄

**Comment by jeffstienstra** [comment]
Buuuuuusted!  Yup :)
